In [6]:
import numpy as np
import tensorflow as tf 
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input
from tensorflow.keras.layers import concatenate
import matplotlib.pyplot as plt
from tensorflow.keras.utils import plot_model
from tensorflow import keras
from tensorflow.keras import layers

In [46]:
#fix random seed for reproductability and generate data
seed=7
np.random.seed(seed)

N = 10**6
X_train = np.zeros(shape=(N,2))
X_train[:][0] = np.linspace(-2.0,2.0,N)
X_train[:][1] = np.linspace(-2.0,2.0,N)

#X1_train = X1_train.reshape([-2.0,2.0])
X_train = tf.Variable(X_train)

X_val = [[],[]]
X_val[0] = np.random.rand(N)
X_val[1] = np.random.rand(N)
X_val[0] = X_val[0].reshape([-2,2])
X_val[0] = np.sort(X_val[0])
X_val[1] = X_val[1].reshape([-2,2])
X_val[1] = np.sort(X_val[1])

ValueError: could not broadcast input array from shape (1000000) into shape (2)

In [45]:
X_train[:][1]

array([0., 0.])

In [32]:
y_train = 1/3*(X_train[0]+1)**3 + X_train[1] + 100*((np.maximum(0,1-X_train[0]))**2+(np.maximum(0,-X_train[1]))**2)

y_val = 1/3*(X_val[0]+1)**3 + X_val[1] + 100*((np.maximum(0,1-X_val[0]))**2+(np.maximum(0,-X_val[1]))**2)

In [33]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(64, input_dim = 2,activation="relu", name="layer1"),
        layers.Dense(32, activation="relu", name="layer2"),
        layers.Dense(1, name="layer3"),
    ]
)

In [35]:
model.compile(optimizer = 'Adam', loss = 'mse' , metrics = ['mse'])

In [37]:
X_train.shape

TensorShape([2, 1000000])

In [36]:
model.fit(X_train, y_train , epochs = 200 , batch_size = 16 , validation_data = (X_val , y_val), verbose = 1)

ValueError: Failed to find data adapter that can handle input: <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>, <class 'tensorflow.python.framework.ops.EagerTensor'>

In [ ]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

def train_step():
    with tf.GradientTape(persistent=True) as tape:
        X_train_1 = tf.cast(X1_train, tf.float32)  # Ensure X_train is float32
        X_train_2 = tf.cast(X2_train, tf.float32)
        y1 = model_1(X_train_1)
        y2 = model_1(X_train_2)
        model_prime = tape.gradient(y, X_train_1)
        loss = tf.reduce_mean(tf.square(model_prime - y)) + (y[0]-1)**2
        grad = tape.gradient(loss, model_1.trainable_variables)
        optimizer.apply_gradients(zip(grad, model_1.trainable_variables))
    
    return loss

In [9]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
np.maximum(0,[1,2,3])

array([1, 2, 3])

In [11]:
np.maximum(0,[-1,3,5,-110])

array([0, 3, 5, 0])